### ISSUE TITLE
no main.py, no example JSON

### ISSUE THREAD

**Issue by nmz787-intel** [Markcanfly/shift-optimizer#1]
the README says to use `main.py` however that file doesn't exist, and it appears `/generate_assignments.py` might be the file meant to be called from the cmd-line.

There is also no example input JSON (as mentioned in `generate_assignments.py`). Can you please update the README (or commit main.py) as well as add an example JSON?

**Comment by markvincevarga** [comment]
Hi! I have since made a simpler version of this at https://github.com/Markcanfly/shifts. Unfortunately I am not going to maintain this repository, so I will archive it as of today.

I recommend you look into the [Python-MIP](https://www.python-mip.com/) project of you want to do something similar, it is far more extensible than the Google OR-Tools framework by using swappable solver backends.

**Comment by Markcanfly** [comment]
As I have no time or plan to maintain this repository, I am unfortunately
